unpackaged/main/default/objects/Issued_Book__c/Issued_Book__c.object-meta.xml
<CustomObject>
    <label>Issued_Book</label>
    <nameField>
        <label>Issued_Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issued_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Issued_Book__c/fields/B_Name__c.field-meta.xml
<CustomField>
    <fullName>B_Name__c</fullName>
    <label>BOOK</label>
    <referenceTo>BOOK__c</referenceTo>
    <relationshipLabel>Issued_Books</relationshipLabel>
    <relationshipName>Issued_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Issued_Book__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Issued_Book__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <label>Penalty</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Issued_Book__c/fields/Return_date__c.field-meta.xml
<CustomField>
    <fullName>Return_date__c</fullName>
    <label>Return date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Issued_Book__c/fields/S_Name__c.field-meta.xml
<CustomField>
    <fullName>S_Name__c</fullName>
    <label>STU</label>
    <referenceTo>STU__c</referenceTo>
    <relationshipLabel>Issued_Books</relationshipLabel>
    <relationshipName>Issued_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Issued_Book__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/STU__c/STU__c.object-meta.xml
<CustomObject>
    <label>STU</label>
    <nameField>
        <label>STUDENT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>STUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/STU__c/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>E_mail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/STU__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/STU__c/fields/S_Name__c.field-meta.xml
<CustomField>
    <fullName>S_Name__c</fullName>
    <label>S_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LibraryHandler.cls
public class LibraryHandler {
    public static void To_Print_Email(list <Issued_Book__c> li){
        set<id> stuid = new set<id>();
        for(Issued_Book__c iss:li){
            stuid.add(iss.S_Name__c);
            //select id will be store into 'set'===>stuid
            system.debug('studid=='+stuid);            
        }
        map<id,STU__c> stuval = new map<id,STU__c>([select id,S_Name__c,E_mail__c,Mobile_No__c from STU__c where id =:stuid]);
        for(Issued_Book__c iss:li){
            //get value from matching record
            iss.E_mail__c= stuval.get(iss.S_Name__c).E_mail__c;
            iss.Mobile_No__c= stuval.get(iss.S_Name__c).Mobile_No__c;
            system.debug('aaaa'+ iss.E_mail__c);
            if(iss.Status__c=='Issued'){
                iss.Issued_Date__c=system.today();
                iss.Return_date__c=system.today()+7; 
                system.debug('today  date is--->'+system.today());
            }
        }
    }
    public static void penalty(list <Issued_Book__c> li){
        for(Issued_Book__c iss:li){
            if(iss.Status__c=='Return' && (iss.Return_Date__c > iss.Issued_Date__c)){
                Integer s = iss.Return_Date__c.daysBetween(iss.Issued_Date__c);
                iss.Penalty__c = s*10;
                system.debug('ssssss'+s);
                System.debug('days count'+iss.Penalty__c);
            }
        }
    }
    public static void permit(list<STU__c> li){   
        
    }
    public static void To_Count_Book(list <Issued_Book__c> li){
        list <String> Book = new list <String> (); 
        set<id> bookid = new set<id>(); 
        for(Issued_Book__c iss1:li){
            bookid.add(iss1.B_Name__c);    
            system.debug('book_id is===>'+bookid);
        }
    }
}